#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ENRICHISSEMENT PHASE 1: Networking & Gaming Categories
Cible: Top 10 categories avec moins de tips (5-10 tips actuellement)
Ajouter 15-20 tips detailles par categorie
"""

file_path = r"C:\Users\Utilisateur\Downloads\Nitrite-V18.5\src\v14_mvp\ai_knowledge_unified.py"

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

insert_point = content.find("        return kb")

# NETWORKING_ROUTER_QOS_GAMING (actuellement 5 tips -> objectif 25)
networking_router_qos = '''
        kb["networking_router_qos_gaming"]["tips"].extend([
            {"content": "QoS priority levels: Set gaming traffic to DSCP EF (Expedited Forwarding, value 46) for highest priority. Use AF41 (34) for streaming, BE (0) for downloads. Configure in router Advanced QoS settings or DD-WRT QoS tab", "keywords": ["qos", "dscp", "priority"], "difficulty": "advanced", "tags": ["configuration"], "related_tools": []},
            {"content": "Bandwidth allocation: Reserve 80-90% for gaming (prevents starvation), 10-20% for other traffic. Never allocate 100% - causes bufferbloat. Example: 1000 Mbps connection = 900 Mbps gaming, 100 Mbps background", "keywords": ["bandwidth", "allocation"], "difficulty": "intermediate", "tags": ["optimization"], "related_tools": []},
            {"content": "Static IP vs DHCP reservation: DHCP reservation (assign same IP to MAC address) better than static IP - no conflicts, automatic fallback. Set in router DHCP settings, use for gaming PC, consoles, streaming devices", "keywords": ["static ip", "dhcp", "reservation"], "difficulty": "intermediate", "tags": ["configuration"], "related_tools": []},
            {"content": "Gaming-specific routers: ASUS RT-AX86U, Netgear Nighthawk XR1000 have DumaOS with geo-filtering (block distant servers), device prioritization, ping heatmaps. Worth upgrade if household has 5+ devices competing for bandwidth", "keywords": ["router", "gaming", "dumaos"], "difficulty": "intermediate", "tags": ["hardware"], "related_tools": []},
            {"content": "UPnP security risk: Universal Plug and Play auto-forwards ports but vulnerable to attacks. For gaming: Enable UPnP for convenience, but manually forward ports for competitive games and disable UPnP. Check port forwarding success with canyouseeme.org", "keywords": ["upnp", "security", "port forwarding"], "difficulty": "intermediate", "tags": ["security"], "related_tools": []},
            {"content": "Router placement optimization: Center of home, elevated 5-6 feet, away from walls/metal/microwaves. 5GHz signal blocked by walls, 2.4GHz penetrates better. For gaming PC: Wired ethernet always superior to WiFi (latency 1-3ms vs 15-30ms)", "keywords": ["placement", "wifi", "signal"], "difficulty": "beginner", "tags": ["optimization"], "related_tools": []},
            {"content": "Firmware updates: Stock firmware gets security updates only, custom firmware (DD-WRT, OpenWrt, Merlin) adds advanced QoS, VPN, overclocking. Check router compatibility at dd-wrt.com. Backup settings before flashing, brick risk if interrupted", "keywords": ["firmware", "dd-wrt", "custom"], "difficulty": "advanced", "tags": ["advanced"], "related_tools": []},
            {"content": "Traffic shaping rules: Create rules in QoS to deprioritize specific apps - Windows Update, Steam downloads, YouTube. Match by port (HTTP 80/443), application, or device MAC. Prevents background downloads from spiking ping", "keywords": ["traffic shaping", "qos rules"], "difficulty": "advanced", "tags": ["configuration"], "related_tools": []},
            {"content": "NAT type for gaming: Open NAT (Type 1) best for matchmaking/voice chat, Moderate (Type 2) acceptable, Strict (Type 3) causes connection issues. Enable UPnP or manually forward game ports to achieve Open NAT. Test in-game or router status page", "keywords": ["nat type", "open nat"], "difficulty": "intermediate", "tags": ["troubleshooting"], "related_tools": []},
            {"content": "Smart Connect disable: Auto band steering (2.4GHz/5GHz) causes disconnects during band switch. Disable Smart Connect, create separate SSIDs for 2.4/5GHz, manually connect gaming devices to 5GHz for lower latency and interference", "keywords": ["smart connect", "band steering"], "difficulty": "intermediate", "tags": ["optimization"], "related_tools": []},
            {"content": "Router CPU bottleneck: Budget routers struggle with QoS at >300 Mbps (CPU maxes out). Symptoms: Ping spikes despite QoS, router web interface laggy. Solution: Upgrade to router with 1+ GHz dual-core CPU (ASUS AX series, Netgear RAX)", "keywords": ["router cpu", "bottleneck"], "difficulty": "intermediate", "tags": ["hardware"], "related_tools": []},
            {"content": "Guest network isolation: Enable guest network for IoT devices, security cameras, smart home. Isolates from main network, prevents compromised devices accessing gaming PC. Configure in router Wireless > Guest Network, disable 'Allow guests to see each other'", "keywords": ["guest network", "isolation", "security"], "difficulty": "intermediate", "tags": ["security"], "related_tools": []},
            {"content": "IPv4 vs IPv6 routing: Some ISPs have poor IPv6 routing (extra hops, higher latency). Test with ping -6 google.com vs ping -4 google.com. If IPv6 slower by >10ms, disable in router WAN settings or Network Adapter properties", "keywords": ["ipv4", "ipv6", "routing"], "difficulty": "intermediate", "tags": ["troubleshooting"], "related_tools": []},
            {"content": "MU-MIMO and OFDMA: MU-MIMO (WiFi 5) serves multiple devices simultaneously, OFDMA (WiFi 6) divides channels for efficiency. Only works if ALL devices support it. For gaming: Wired connection still superior, MU-MIMO helps household congestion", "keywords": ["mu-mimo", "ofdma", "wifi 6"], "difficulty": "intermediate", "tags": ["knowledge"], "related_tools": []},
            {"content": "Beamforming technology: Focuses WiFi signal towards devices instead of broadcasting omnidirectionally. Improves signal strength 10-20%, reduces interference. Enable in router wireless settings. Works best with WiFi 5/6 devices, minimal impact on WiFi 4", "keywords": ["beamforming", "signal strength"], "difficulty": "beginner", "tags": ["optimization"], "related_tools": []},
        ])
'''

# NETWORKING_DNS_OPTIMIZATION (actuellement 6 tips -> objectif 25)
networking_dns = '''
        kb["networking_dns_optimization"]["tips"].extend([
            {"content": "DNS lookup time: Measures time to resolve domain to IP. Cloudflare 1.1.1.1 averages 10-15ms, Google 8.8.8.8 averages 20-30ms, ISP DNS varies 30-100ms. Test with namebench or DNS Benchmark tool. Faster DNS = quicker initial page loads", "keywords": ["dns", "lookup time", "speed"], "difficulty": "beginner", "tags": ["testing"], "related_tools": ["namebench"]},
            {"content": "DNS cache poisoning protection: DNSSEC validates DNS responses prevent man-in-middle attacks. Cloudflare and Quad9 support DNSSEC. Enable in router DNS settings if available. Check dnssec-failed.org - should show error, not load", "keywords": ["dnssec", "security", "cache poisoning"], "difficulty": "advanced", "tags": ["security"], "related_tools": []},
            {"content": "DNS over HTTPS (DoH): Encrypts DNS queries, prevents ISP tracking. Firefox has built-in DoH (Settings > Network > Enable DNS over HTTPS). Windows 11: Settings > Network > Ethernet/WiFi > DNS > Prefer encrypted. Uses Cloudflare/Google DoH servers", "keywords": ["doh", "dns over https", "privacy"], "difficulty": "intermediate", "tags": ["privacy"], "related_tools": []},
            {"content": "DNS over TLS (DoT): Similar to DoH but uses TLS port 853 instead of HTTPS 443. Android 9+ supports Private DNS (Settings > Network > Private DNS > dns.google). Less likely blocked by firewalls than DoH, but easier to detect/block by ISP", "keywords": ["dot", "dns over tls"], "difficulty": "advanced", "tags": ["privacy"], "related_tools": []},
            {"content": "Local DNS caching: Windows DNS Client service caches recent lookups. Check cache with ipconfig /displaydns, clear with ipconfig /flushdns. Reduces repeat lookups from 20ms to <1ms. Issue: stale cache after DNS changes - flush to fix", "keywords": ["dns cache", "flush"], "difficulty": "beginner", "tags": ["troubleshooting"], "related_tools": []},
            {"content": "NextDNS custom filtering: Free tier 300k queries/month, blocks ads, trackers, malware at DNS level (no client needed). Create account at nextdns.io, get custom DNS IPs, configure device/router. Includes parental controls, analytics dashboard", "keywords": ["nextdns", "ad blocking", "dns filtering"], "difficulty": "intermediate", "tags": ["privacy"], "related_tools": []},
            {"content": "Pi-hole network-wide blocking: Raspberry Pi DNS sinkhole blocks ads for entire network. Blocks 100k+ domains, dashboard shows queries/blocks, no per-device configuration. Install with curl -sSL https://install.pi-hole.net | bash. Requires Pi 3/4, 1+ GB SD card", "keywords": ["pi-hole", "network blocking", "raspberry pi"], "difficulty": "advanced", "tags": ["advanced"], "related_tools": ["Pi-hole"]},
            {"content": "DNS failover configuration: Set primary and secondary DNS for redundancy. Example: Primary 1.1.1.1, Secondary 8.8.8.8. If primary fails, switches to secondary in 3-5 seconds. Configure in Network Adapter > IPv4 > Alternate DNS server", "keywords": ["dns failover", "redundancy"], "difficulty": "beginner", "tags": ["reliability"], "related_tools": []},
            {"content": "Gaming-optimized DNS: Cloudflare 1.1.1.1 and Google 8.8.8.8 have low latency, global anycast network (connects to nearest server). Avoid ISP DNS - often slow, logs queries, hijacks NXDOMAIN (non-existent domain) for ads", "keywords": ["gaming dns", "cloudflare", "google"], "difficulty": "beginner", "tags": ["gaming"], "related_tools": []},
            {"content": "DNS rebinding protection: Router security feature prevents malicious sites from accessing local network. Can break Plex, Chromecast, local dev servers. Whitelist domains in router security settings or disable rebinding protection temporarily for troubleshooting", "keywords": ["dns rebinding", "security"], "difficulty": "advanced", "tags": ["security"], "related_tools": []},
            {"content": "Public DNS privacy comparison: Cloudflare 1.1.1.1 claims no logging (audited), Google 8.8.8.8 logs temporarily for diagnostics, Quad9 9.9.9.9 blocks malware domains, OpenDNS 208.67.222.222 customizable filtering. For max privacy: Cloudflare or self-hosted Pi-hole", "keywords": ["privacy", "logging", "dns providers"], "difficulty": "intermediate", "tags": ["privacy"], "related_tools": []},
            {"content": "TTL (Time To Live): DNS record lifespan in cache. Low TTL (300s) = frequent lookups/current data, high TTL (86400s) = fewer lookups/stale data. Gaming: no impact, Web dev: lower TTL when testing DNS changes, raise after stable", "keywords": ["ttl", "time to live"], "difficulty": "intermediate", "tags": ["knowledge"], "related_tools": []},
            {"content": "EDNS Client Subnet: Sends partial IP to DNS for geolocation (CDN routing). Privacy concern - leaks location. Cloudflare 1.1.1.1 does NOT send ECS (better privacy), Google 8.8.8.8 sends ECS (better CDN performance). Trade-off: privacy vs speed", "keywords": ["edns", "client subnet", "privacy"], "difficulty": "advanced", "tags": ["privacy"], "related_tools": []},
            {"content": "DNS benchmark methodology: Use DNS Benchmark tool, test 50+ DNS servers, run 10000+ queries. Metrics: cached lookup time, uncached time, dotcom time. Choose server with lowest uncached (most important for browsing). Re-test every 6 months (routing changes)", "keywords": ["benchmark", "testing"], "difficulty": "intermediate", "tags": ["testing"], "related_tools": ["DNS Benchmark"]},
        ])
'''

# NETWORKING_ETHERNET_OPTIMIZATION (actuellement 6 tips -> objectif 25)
networking_ethernet = '''
        kb["networking_ethernet_optimization"]["tips"].extend([
            {"content": "Flow Control (802.3x): Prevents packet loss when receiver buffer full. Disable in adapter properties for gaming - adds 1-3ms latency. Enable for NAS/file transfers. Set to 'Disabled' in Device Manager > Adapter > Properties > Advanced > Flow Control", "keywords": ["flow control", "latency"], "difficulty": "advanced", "tags": ["optimization"], "related_tools": []},
            {"content": "Interrupt Moderation: Groups packets to reduce CPU interrupts. Default 'Enabled' adds 0.5-2ms latency but reduces CPU load 5-10%. For gaming: Disable. For streaming/recording: Enable (reduces frame drops). Toggle in adapter advanced settings", "keywords": ["interrupt moderation", "latency"], "difficulty": "advanced", "tags": ["optimization"], "related_tools": []},
            {"content": "Receive Side Scaling (RSS): Distributes network processing across multiple CPU cores. Enable for 4+ core CPUs to reduce single-core bottleneck. Queues = CPU cores (8 cores = 8 queues). Check in adapter properties, affects throughput not latency", "keywords": ["rss", "receive side scaling"], "difficulty": "advanced", "tags": ["performance"], "related_tools": []},
            {"content": "Jumbo Frames: Increases MTU from 1500 to 9000 bytes, reduces overhead 10-20% for large transfers. ONLY enable if entire network supports it (router, switches, NAS). Gaming: no benefit, can cause issues. File transfers: +100-200 MB/s throughput", "keywords": ["jumbo frames", "mtu"], "difficulty": "expert", "tags": ["advanced"], "related_tools": []},
            {"content": "Large Send Offload (LSO/TSO): Offloads TCP segmentation to network card, reduces CPU usage. Disable for gaming - can add 2-5ms latency, Enable for streaming/downloads. Set in adapter properties > Advanced > Large Send Offload v2 (IPv4/IPv6)", "keywords": ["lso", "tso", "offload"], "difficulty": "advanced", "tags": ["optimization"], "related_tools": []},
            {"content": "Energy Efficient Ethernet (EEE/802.3az): Reduces power by slowing link during idle. Causes 10-50ms wake latency spikes. Disable for gaming in adapter advanced settings. Also disable in router/switch if option available. Savings: 0.5-1W (negligible)", "keywords": ["eee", "energy efficient", "latency"], "difficulty": "intermediate", "tags": ["optimization"], "related_tools": []},
            {"content": "Speed/Duplex auto-negotiation: Normally leave at 'Auto Negotiation', but if getting 100 Mbps on Gigabit adapter, manually set to '1.0 Gbps Full Duplex'. Half duplex causes collisions/packet loss. Verify link speed in adapter status", "keywords": ["speed duplex", "auto negotiation"], "difficulty": "intermediate", "tags": ["troubleshooting"], "related_tools": []},
            {"content": "Receive Buffers: Increase from default 512 to 2048-4096 for high-speed connections (Gigabit+), reduces packet drops during bursts. Gaming impact minimal, helps 4K streaming, large downloads. Set in adapter properties > Advanced > Receive Buffers", "keywords": ["receive buffers", "packet loss"], "difficulty": "advanced", "tags": ["optimization"], "related_tools": []},
            {"content": "Checksum Offload: Offloads TCP/UDP checksum calculation to NIC. Normally leave enabled (reduces CPU 1-2%), but if experiencing corrupted packets, disable IPv4/IPv6 Checksum Offload in adapter advanced settings. Rare issue with cheap/old NICs", "keywords": ["checksum offload"], "difficulty": "advanced", "tags": ["troubleshooting"], "related_tools": []},
            {"content": "Cable quality testing: TDR (Time Domain Reflectometry) in high-end NICs detects cable faults, crosstalk, length. Intel NICs have diagnostics in driver package. Symptoms of bad cable: random disconnects, 100 Mbps instead of 1 Gbps, high error counts", "keywords": ["cable testing", "tdr"], "difficulty": "intermediate", "tags": ["diagnostics"], "related_tools": []},
            {"content": "Power Management: 'Allow computer to turn off device to save power' causes random disconnects. Disable in Device Manager > Adapter > Power Management tab. Also disable 'Allow this device to wake computer' if getting random wake from sleep", "keywords": ["power management", "disconnects"], "difficulty": "beginner", "tags": ["troubleshooting"], "related_tools": []},
            {"content": "VLAN tagging (802.1Q): Segments network traffic, useful for separating gaming/IoT/work. Requires managed switch and router. Tag gaming traffic as VLAN 10, give QoS priority. Configure in switch management interface and adapter properties (if NIC supports)", "keywords": ["vlan", "tagging", "segmentation"], "difficulty": "expert", "tags": ["advanced"], "related_tools": []},
            {"content": "Link Aggregation (LACP/802.3ad): Combines 2+ ethernet ports for redundancy or increased bandwidth. Requires managed switch. Gaming: no benefit (single connection), NAS/server: doubles throughput (2 Gbps). Configure in switch and NIC teaming software", "keywords": ["link aggregation", "lacp"], "difficulty": "expert", "tags": ["advanced"], "related_tools": []},
            {"content": "Direct Cable Connection: Bypass router by connecting PC directly to modem (PPPoE/DHCP). Eliminates router latency 1-3ms, but loses firewall protection, WiFi, device sharing. For competitive gaming only, reconnect router after session", "keywords": ["direct connection", "bypass router"], "difficulty": "intermediate", "tags": ["competitive"], "related_tools": []},
        ])
'''

# WINDOWS_11_REGISTRY_TWEAKS (actuellement 7 tips -> objectif 25)
windows_registry = '''
        kb["windows_11_registry_tweaks"]["tips"].extend([
            {"content": "Disable Nagle Algorithm: Reduces TCP latency by disabling packet batching. Regedit: HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Services\\\\Tcpip\\\\Parameters\\\\Interfaces\\\\{GUID}\\\\TcpAckFrequency = 1, TCPNoDelay = 1. Find GUID in ipconfig /all. Requires reboot, reduces latency 10-30ms", "keywords": ["nagle", "tcp", "latency"], "difficulty": "expert", "tags": ["networking"], "related_tools": []},
            {"content": "Network Throttling Index: Windows limits network usage to 80% by default. Set to FFFFFFFF (hex) to disable: HKLM\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Multimedia\\\\SystemProfile\\\\NetworkThrottlingIndex. Improves streaming, downloading. Reboot required", "keywords": ["network throttling", "bandwidth"], "difficulty": "advanced", "tags": ["networking"], "related_tools": []},
            {"content": "SystemResponsiveness: Priority for background tasks. Default 20 (20% CPU reserved). Set to 0 for gaming (background tasks get minimal priority): HKLM\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Multimedia\\\\SystemProfile\\\\SystemResponsiveness. Reboot required", "keywords": ["system responsiveness", "priority"], "difficulty": "advanced", "tags": ["performance"], "related_tools": []},
            {"content": "GPU Priority: Increase priority for games. HKLM\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Multimedia\\\\SystemProfile\\\\Tasks\\\\Games\\\\GPU Priority = 8 (default 2), Priority = 6 (default 2). Gives games more GPU time slice. Reboot required", "keywords": ["gpu priority", "gaming"], "difficulty": "advanced", "tags": ["gaming"], "related_tools": []},
            {"content": "Disable HPET (High Precision Event Timer): Can reduce performance in some games. bcdedit /deletevalue useplatformclock in Command Prompt (Admin). Verify in Task Manager > Performance > CPU > 'Platform' should show 'Disabled'. Revert with bcdedit /set useplatformclock true", "keywords": ["hpet", "timer"], "difficulty": "advanced", "tags": ["gaming"], "related_tools": []},
            {"content": "SvcHostSplitThresholdInKB: Separate services into individual processes. Default 3670016 (3.5GB RAM). For 16GB+ RAM, increase to 8388608 (8GB): HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\SvcHostSplitThresholdInKB. Improves stability, increases RAM usage 200-500MB. Reboot required", "keywords": ["svchost", "services"], "difficulty": "expert", "tags": ["advanced"], "related_tools": []},
            {"content": "Disable Spectre/Meltdown mitigations: Increases performance 5-10% but security risk. For gaming PC not handling sensitive data: HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\Session Manager\\\\Memory Management\\\\FeatureSettingsOverride = 3, FeatureSettingsOverrideMask = 3. Reboot required", "keywords": ["spectre", "meltdown", "security"], "difficulty": "expert", "tags": ["performance"], "related_tools": []},
            {"content": "Menu Show Delay: Speed up right-click context menu. HKCU\\\\Control Panel\\\\Desktop\\\\MenuShowDelay = 0 (instant, default 400ms). Applies immediately, no reboot. Too fast can feel twitchy, 100-200 is balanced", "keywords": ["menu delay", "context menu"], "difficulty": "beginner", "tags": ["usability"], "related_tools": []},
            {"content": "Disable Windows Defender real-time: NOT recommended, but for benchmarking: HKLM\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows Defender\\\\DisableAntiSpyware = 1. Gives 2-5% FPS boost. Re-enable after testing. Use exclusions instead (add game folders to Virus & threat protection > Exclusions)", "keywords": ["windows defender", "exclusions"], "difficulty": "intermediate", "tags": ["gaming"], "related_tools": []},
            {"content": "Win32PrioritySeparation: CPU scheduling priority. Default 2 (26 hex). For gaming set to 38 (hex): HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\PriorityControl\\\\Win32PrioritySeparation. Values: 26 = balanced, 38 = favor foreground, 18 = favor background. Reboot required", "keywords": ["priority separation", "scheduling"], "difficulty": "expert", "tags": ["performance"], "related_tools": []},
            {"content": "Disable Prefetch/Superfetch on SSD: Unnecessary on SSDs, slight overhead. HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Control\\\\Session Manager\\\\Memory Management\\\\PrefetchParameters\\\\EnablePrefetcher = 0, EnableSuperfetch = 0. Or disable SysMain service. HDD: keep enabled", "keywords": ["prefetch", "superfetch", "ssd"], "difficulty": "intermediate", "tags": ["optimization"], "related_tools": []},
            {"content": "Increase IRPStackSize: Fixes 'default too small' errors with network shares. HKLM\\\\SYSTEM\\\\CurrentControlSet\\\\Services\\\\LanmanServer\\\\Parameters\\\\IRPStackSize = 20 (default 15). Improves network stability. Reboot required", "keywords": ["irpstacksize", "network shares"], "difficulty": "advanced", "tags": ["networking"], "related_tools": []},
            {"content": "Disable Program Compatibility Assistant: Prevents popup asking to reinstall with 'recommended settings'. HKLM\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\Windows\\\\AppCompat\\\\DisablePCA = 1. Or disable via services: Program Compatibility Assistant Service > Disabled", "keywords": ["compatibility assistant"], "difficulty": "beginner", "tags": ["usability"], "related_tools": []},
            {"content": "Backup before registry edits: Create restore point (sysdm.cpl > System Protection > Create) and export registry key (Regedit > Right-click key > Export). If system breaks, boot Safe Mode > restore point or double-click exported .reg file", "keywords": ["backup", "restore point"], "difficulty": "beginner", "tags": ["safety"], "related_tools": []},
        ])
'''

# GAMING_FPS_OPTIMIZATION_AAA (actuellement 7 tips -> objectif 25)
gaming_aaa = '''
        kb["gaming_fps_optimization_aaa"]["tips"].extend([
            {"content": "Resolution scaling: Render at 70-90% native res, upscale with DLSS/FSR/XeSS. Cyberpunk 2077: 1440p DLSS Quality mode renders at 960p upscaled, gives +40% FPS with 95% visual quality. Better than lowering native resolution (blurry UI)", "keywords": ["resolution scaling", "dlss", "fsr"], "difficulty": "intermediate", "tags": ["graphics"], "related_tools": []},
            {"content": "Ray tracing cost: RT Reflections 20-30% FPS cost, RT Shadows 10-15%, RT Global Illumination 30-40%, RT Ambient Occlusion 5-10%. Disable RT GI first (biggest cost), keep RT Reflections if FPS allows. DLSS/FSR required for RT at 60+ FPS on mid-range GPUs", "keywords": ["ray tracing", "performance cost"], "difficulty": "intermediate", "tags": ["graphics"], "related_tools": []},
            {"content": "Texture quality: VRAM-limited setting. High vs Ultra: <5% FPS difference, 2-4GB VRAM increase. Use High on 8GB cards, Ultra on 12GB+. If textures look blurry after loading, VRAM bottleneck - lower to High or Medium", "keywords": ["texture quality", "vram"], "difficulty": "beginner", "tags": ["graphics"], "related_tools": []},
            {"content": "Shadow quality: CPU-bound setting. High to Low can give 10-20% FPS boost on weak CPUs. GPU impact minimal. Reduce shadow distance/cascades first, then quality. Competitive: Low shadows, Single-player: Medium-High acceptable", "keywords": ["shadow quality", "cpu bound"], "difficulty": "intermediate", "tags": ["graphics"], "related_tools": []},
            {"content": "Volumetric effects: Fog, clouds, god rays. Very expensive 15-25% FPS cost for minor visual improvement. Red Dead Redemption 2: Volumetric Lighting from Ultra to Medium gives +20 FPS. Set to Low/Medium unless abundant GPU headroom", "keywords": ["volumetric", "fog", "performance"], "difficulty": "intermediate", "tags": ["graphics"], "related_tools": []},
            {"content": "Motion blur disable: Adds no visual quality for screenshots, makes motion harder to track. Always disable for sharper image and clarity. Found in Graphics > Post-Processing. Exception: Cinematic games (The Last of Us) where blur enhances film-like feel", "keywords": ["motion blur", "clarity"], "difficulty": "beginner", "tags": ["graphics"], "related_tools": []},
            {"content": "Depth of Field disable: Blurs background for realism, but obscures environment. Disable for competitive advantage and clarity. Single-player: personal preference. Minimal FPS impact (1-3%), purely visual choice", "keywords": ["depth of field", "dof"], "difficulty": "beginner", "tags": ["graphics"], "related_tools": []},
            {"content": "Ambient Occlusion methods: SSAO (fast, low quality), HBAO+ (balanced), RT AO (expensive, realistic). SSAO to HBAO+: 5% FPS cost, noticeable quality. HBAO+ to RT AO: 15% FPS cost, subtle improvement. Use HBAO+ for balance", "keywords": ["ambient occlusion", "ssao", "hbao"], "difficulty": "intermediate", "tags": ["graphics"], "related_tools": []},
            {"content": "LOD (Level of Detail) distance: Controls when objects switch to low-poly models. Increasing costs GPU/VRAM, decreasing causes pop-in. Medium-High balanced for most games. Flight/racing sims: High-Ultra (see far), FPS games: Medium (close combat)", "keywords": ["lod", "draw distance"], "difficulty": "intermediate", "tags": ["graphics"], "related_tools": []},
            {"content": "Foliage/vegetation: GPU and CPU intensive (physics simulation). High to Low can give 15-20% FPS boost in dense areas (forests, jungles). Reduces visual immersion significantly. Competitive: Low, Single-player: Medium-High", "keywords": ["foliage", "vegetation"], "difficulty": "intermediate", "tags": ["graphics"], "related_tools": []},
            {"content": "Crowd density: NPCs in cities/events. CPU-bound, affects frametime consistency more than average FPS. Cyberpunk 2077, Assassin's Creed: High to Low gives +10 FPS, smoother frametimes. Medium balanced for visual/performance", "keywords": ["crowd density", "npcs"], "difficulty": "intermediate", "tags": ["graphics"], "related_tools": []},
            {"content": "Anisotropic Filtering: Sharpens textures at angles. 16x AF costs <1% FPS on modern GPUs. Always max out (16x) for free visual quality improvement. One of few settings to always enable at highest", "keywords": ["anisotropic filtering", "af"], "difficulty": "beginner", "tags": ["graphics"], "related_tools": []},
            {"content": "V-Sync alternatives: Adaptive VSync (NVIDIA): VSync on above refresh rate, off below (reduces input lag). Enhanced Sync (AMD): Similar to Adaptive. Both better than traditional VSync. Or use G-Sync/FreeSync and cap FPS 3 below refresh (117 for 120Hz)", "keywords": ["vsync", "adaptive sync"], "difficulty": "intermediate", "tags": ["synchronization"], "related_tools": []},
            {"content": "Game-specific tweaks: Cyberpunk 2077: Disable RT Lighting, RDR2: Hardware.XML tweaks (volmetricLightingQuality=0), Starfield: Disable VSync in .ini. Research game-specific optimization guides on PCGamingWiki.com for hidden settings", "keywords": ["game specific", "ini tweaks"], "difficulty": "advanced", "tags": ["advanced"], "related_tools": []},
            {"content": "Shader precompilation: Games like Forza, COD precompile shaders on launch. Let complete fully before playing (5-10 minutes). Skipping causes stutters during gameplay. Progress bar in bottom-right or separate window", "keywords": ["shader precompilation", "stuttering"], "difficulty": "beginner", "tags": ["optimization"], "related_tools": []},
            {"content": "DX11 vs DX12: DX12 lower CPU overhead (better FPS on weak CPUs, multi-threaded), but more bugs/stutters. DX11 more stable, higher single-thread CPU usage. Test both, use DX12 if <10% stutters, DX11 if constant hitching. Vulkan (Red Dead 2) often best", "keywords": ["dx11", "dx12", "vulkan"], "difficulty": "intermediate", "tags": ["api"], "related_tools": []},
        ])
'''

# GAMING_FPS_OPTIMIZATION_COMPETITIVE (actuellement 7 tips -> objectif 25)
gaming_competitive = '''
        kb["gaming_fps_optimization_competitive"]["tips"].extend([
            {"content": "Competitive graphics priority: Visibility > Clarity > FPS > Visual Quality. Disable: Shadows (enemy hiding), Motion Blur (tracking), Bloom (bright spots), Lens Flare (sun glare), Ambient Occlusion (dark corners). Enable: High textures (skin clarity), AA (jagged edges)", "keywords": ["competitive", "visibility"], "difficulty": "intermediate", "tags": ["competitive"], "related_tools": []},
            {"content": "Render scale exploit: Valorant, Overwatch 2 allow 50-100% render scale. 50% gives massive FPS boost but blurry. 75% balanced for 144Hz, 100% for 240Hz+. Enemy models still visible at 75%, UI stays sharp. Crosshair unaffected", "keywords": ["render scale", "competitive"], "difficulty": "intermediate", "tags": ["competitive"], "related_tools": []},
            {"content": "Exclusive Fullscreen vs Borderless: Exclusive 5-10ms lower latency (direct GPU access, no DWM), Borderless easier alt-tab, +5-10ms latency. Competitive: Force Exclusive (disable Fullscreen Optimizations in .exe properties). Check with PresentMon or CapFrameX", "keywords": ["exclusive fullscreen", "latency"], "difficulty": "advanced", "tags": ["competitive"], "related_tools": []},
            {"content": "Framerate cap strategy: Cap 3-5 FPS below monitor refresh to prevent tearing with G-Sync/FreeSync. 240Hz monitor: cap 235 FPS. Uncapped causes GPU usage spikes, frametime variance. Use in-game limiter (lowest latency) or RTSS (universal)", "keywords": ["framerate cap", "fps limit"], "difficulty": "intermediate", "tags": ["competitive"], "related_tools": ["RTSS"]},
            {"content": "Reflex Low Latency (NVIDIA): Reduces input lag 10-20ms by syncing CPU/GPU, reducing render queue. Valorant, Fortnite, Apex support it. Enable Reflex + Boost in-game. Boost increases GPU clocks (5W more power, 1-2ms lower latency). Always enable for competitive", "keywords": ["reflex", "low latency", "nvidia"], "difficulty": "intermediate", "tags": ["competitive"], "related_tools": []},
            {"content": "Anti-Lag (AMD): Similar to Reflex, reduces input lag 10-15ms. Enable in AMD Software > Gaming > Graphics > Radeon Anti-Lag. Works in most DX9/11 games. Can cause crashes in anti-cheat games - test in practice mode first", "keywords": ["anti-lag", "amd"], "difficulty": "intermediate", "tags": ["competitive"], "related_tools": []},
            {"content": "Latency testing: Use LDAT (Latency Display Analysis Tool, $200), or NVIDIA Reflex Latency Analyzer (compatible G-Sync monitors + mice). Measures end-to-end latency (click to pixel). Baseline: 30-50ms good, 20-30ms excellent, <20ms pro-level", "keywords": ["latency testing", "ldat"], "difficulty": "advanced", "tags": ["testing"], "related_tools": []},
            {"content": "Monitor overclocking: Many 144Hz monitors overclock to 165-180Hz. Use CRU (Custom Resolution Utility), create custom resolution, increase refresh rate by 10Hz, test stability with UFO test. Reduces frame persistence, smoother motion. Risk: monitor damage if excessive", "keywords": ["monitor overclocking", "refresh rate"], "difficulty": "expert", "tags": ["advanced"], "related_tools": ["CRU"]},
            {"content": "Polling rate impact: 1000Hz mouse polling adds 0.5-1ms latency vs 125Hz, but smoother tracking. CPU usage increases 1-2%. Use 1000Hz on modern CPUs, 500Hz if <4 cores. Keyboard: 1000Hz negligible impact, always use max", "keywords": ["polling rate", "mouse"], "difficulty": "intermediate", "tags": ["peripherals"], "related_tools": []},
            {"content": "Audio positioning: Stereo better than surround for competitive (clearer directional cues). Disable Sonic/Atmos, use stereo in-game. For surround: use game's built-in HRTF (Valorant, CS2), not Windows Sonic. Footsteps: boost 1-4 kHz range in Equalizer APO", "keywords": ["audio", "positioning", "stereo"], "difficulty": "intermediate", "tags": ["audio"], "related_tools": ["Equalizer APO"]},
            {"content": "Network settings priority: In-game server region closest to you (<20ms ping), prefer Ethernet over WiFi, QoS router priority, close bandwidth-heavy background apps (Discord streaming, browser). Test ping to servers with game's built-in server browser", "keywords": ["network", "ping", "servers"], "difficulty": "beginner", "tags": ["networking"], "related_tools": []},
            {"content": "Warmup routine: 10-15 mins aim trainer (Aim Lab, Kovaak's) before ranked. Muscle memory activation, reaction time improves 50-100ms after warmup. Track stats over time to identify consistency issues (sleep, stress, diet affect reaction)", "keywords": ["warmup", "aim training"], "difficulty": "beginner", "tags": ["practice"], "related_tools": ["Aim Lab"]},
            {"content": "Config optimization: Reduce clutter - minimal HUD, hide kill feed, large crosshair, bright enemy outlines. Valorant: Enemy Highlight Yellow, Outline Thickness 1. CS2: cl_hud_color 5 (yellow), viewmodel_fov 68 (wider FOV). Clarity > aesthetics", "keywords": ["config", "hud", "visibility"], "difficulty": "intermediate", "tags": ["settings"], "related_tools": []},
            {"content": "Replay analysis: Record gameplay (NVIDIA ShadowPlay 50 Mbps, OBS 40 Mbps CQP 18), review deaths for mistakes. 70% deaths = positioning error, 20% = aim error, 10% = game sense. Focus improvement on positioning (crosshair placement, cover usage)", "keywords": ["replay", "analysis", "improvement"], "difficulty": "beginner", "tags": ["improvement"], "related_tools": ["ShadowPlay", "OBS"]},
            {"content": "Anti-cheat considerations: Some tweaks trigger AC - MSI mode, core affinity, ReShade, memory tweakers. Valorant Vanguard very strict, CS2 VAC moderate, Fortnite EAC moderate. Test in casual before ranked, never use injectors/overlays in competitive", "keywords": ["anti-cheat", "vanguard", "vac"], "difficulty": "intermediate", "tags": ["security"], "related_tools": []},
        ])
'''

# Assembler toutes les additions
all_additions = networking_router_qos + networking_dns + networking_ethernet + windows_registry + gaming_aaa + gaming_competitive

# Construire nouveau contenu
new_content = content[:insert_point] + all_additions + "\n" + content[insert_point:]

# Ecrire
with open(file_path, 'w', encoding='utf-8') as f:
    f.write(new_content)

# Tester import
import sys
sys.path.insert(0, r"C:\Users\Utilisateur\Downloads\Nitrite-V18.5\src")
if 'v14_mvp.ai_knowledge_unified' in sys.modules:
    del sys.modules['v14_mvp.ai_knowledge_unified']

from v14_mvp.ai_knowledge_unified import UnifiedKnowledgeBase
kb = UnifiedKnowledgeBase()
stats = kb.get_stats()

print(f"\n{'='*80}")
print(f"  ENRICHISSEMENT PHASE 1 COMPLETE!")
print(f"{'='*80}")
print(f"  Categories enrichies: 6 (Networking + Gaming AAA/Competitive + Registry)")
print(f"  Conseils ajoutes: ~90 (15 par categorie)")
print(f"  RESULTAT:")
print(f"    Categories: {stats['categories']}/143 ({stats['categories']/143*100:.1f}%)")
print(f"    Conseils: {stats['tips']}/5000 ({stats['tips']/5000*100:.1f}%)")
print(f"    Moyenne: {stats['tips']/stats['categories']:.1f} conseils/categorie")
print(f"  PROGRESSION: {stats['tips']/5000*100:.1f}% vers objectif 5000")
print(f"{'='*80}\n")
